name: Streamlit Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Use your requirements file

    - name: Deploy Streamlit app
      run: streamlit run animal.py # Replace 'app.py' with the name of your Streamlit app script
